var testMap = {
    "name":"TestMap",
    "size":5,
    "map":[
        {
            "x":0,
            "y":0,
            "water":false,
            "biom":"grass"
        },
        {
            "x":1,
            "y":0,
            "obj":"tree"
        },
        {
            "x":1,
            "y":0,
            "water":false,
            "biom":"grass"
        },
        {
            "x":2,
            "y":0,
            "water":false,
            "biom":"grass"
        },
        {
            "x":3,
            "y":0,
            "water":false,
            "biom":"grass"
        },
        {
            "x":4,
            "y":0,
            "water":true
        },
        {
            "x":0,
            "y":1,
            "water":false,
            "biom":"grass"
        },
        {
            "x":1,
            "y":1,
            "water":true,
            "biom":"grass"
        },
        {
            "x":2,
            "y":1,
            "water":false,
            "biom":"grass"
        },
        {
            "x":3,
            "y":1,
            "water":false,
            "biom":"grass"
        },
        {
            "x":4,
            "y":1,
            "water":true
        },
        {
            "x":0,
            "y":2,
            "water":false,
            "biom":"grass"
        },
        {
            "x":1,
            "y":2,
            "water":false,
            "biom":"grass"
        },
        {
            "x":2,
            "y":2,
            "water":false,
            "biom":"grass"
        },
        {
            "x":3,
            "y":2,
            "water":false,
            "biom":"grass"
        },
        {
            "x":4,
            "y":2,
            "water":true
        },
        {
            "x":0,
            "y":3,
            "water":false,
            "biom":"grass"
        },
        {
            "x":1,
            "y":3,
            "water":false,
            "biom":"grass"
        },
        {
            "x":2,
            "y":3,
            "water":false,
            "biom":"grass"
        },
        {
            "x":3,
            "y":3,
            "water":false,
            "biom":"grass"
        },
        {
            "x":3,
            "y":3,
            "obj":"hero",
            "owner":"red"
        },
        {
            "x":4,
            "y":3,
            "water":true
        },
        {
            "x":0,
            "y":4,
            "water":false,
            "biom":"grass"
        },
        {
            "x":1,
            "y":4,
            "water":false,
            "biom":"grass"
        },
        {
            "x":2,
            "y":4,
            "water":false,
            "biom":"grass"
        },
        {
            "x":3,
            "y":4,
            "water":false,
            "biom":"grass"
        },
        {
            "x":4,
            "y":4,
            "water":true
        }
    ]
}
var newMap = {
    "name":"newMap",
    "height":"6",
    "width":"6",
    "map":{
        "ground":[
            {
                "x":0,
                "y":0,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":1,
                "y":0,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":2,
                "y":0,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":3,
                "y":0,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":4,
                "y":0,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":5,
                "y":0,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":0,
                "y":1,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":1,
                "y":1,
                "type":"water",
                "biom":"ocean"
            },
            {
                "x":2,
                "y":1,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":3,
                "y":1,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":4,
                "y":1,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":5,
                "y":1,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":0,
                "y":2,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":1,
                "y":2,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":2,
                "y":2,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":3,
                "y":2,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":4,
                "y":2,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":5,
                "y":2,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":0,
                "y":3,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":1,
                "y":3,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":2,
                "y":3,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":3,
                "y":3,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":4,
                "y":3,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":5,
                "y":3,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":0,
                "y":4,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":1,
                "y":4,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":2,
                "y":4,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":3,
                "y":4,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":4,
                "y":4,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":5,
                "y":4,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":0,
                "y":5,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":1,
                "y":5,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":2,
                "y":5,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":3,
                "y":5,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":4,
                "y":5,
                "type":"land",
                "biom":"grass"
            },
            {
                "x":5,
                "y":5,
                "type":"land",
                "biom":"grass"
            },
        ],
        "terrain":[
            {
                "x":1,
                "y":4,
                "type":"tree",
                "biom":"oak"
            },
            {
                "x":2,
                "y":2,
                "type":"tree",
                "biom":"oak"
            },
            {
                "x":2,
                "y":3,
                "type":"mountain",
                "biom":"rock"
            },
        ],
        "structures":[

        ],
        "objects":[
            {
                "x":4,
                "y":1,
                "type":"castle_fort_t1",
                "owner":"red"
            },
            {
                "x":4,
                "y":3,
                "type":"hero",
                "owner":"red"
            },
            {
                "x":5,
                "y":5,
                "type":"wood"
            }
        ]
    }
}
